name: Docker Image CI
run-name: ${{ github.actor }} execute after pushes ğŸš€

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: kube

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login Docker
        run: docker login -u ahlirobot -p ${{ vars.GITLABPASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ahlirobot/live-audio:latest --build-arg GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
      - name: Push the Docker image
        run: docker push ahlirobot/live-audio:latest
      - name: run the docker
        run: kubectl rollout restart deployment/live-audio-deployment -n bot || true
